server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API-kall til backenden hvis du ikke bruker full URL i frontenden
    location /api/ {
        proxy_pass http://backend:8080;
    }
}