// Code generated by tygo. DO NOT EDIT.

//////////
// source: form.go
/*
models.go
*/

export interface MemberType {
  id: any /* types.CompactUUID */;
  name: string;
}
export interface GetFormResponse {
  formId: any /* types.CompactUUID */;
  clubId: string;
  memberTypes: MemberType[];
  title: string;
  registrationOpens: string /* RFC3339 */;
}

//////////
// source: registration.go
/*
models.go
*/

export interface CreateRegistrationRequest {
  memberId: any /* types.CompactUUID */;
  formId: any /* types.CompactUUID */;
  memberTypeId: any /* types.CompactUUID */;
  name: string;
  email: string;
  phoneNumber: string;
  birthDate: string /* RFC3339 */;
}
export interface CreateRegistrationResponse {
  id: any /* types.CompactUUID */;
  formId: any /* types.CompactUUID */;
  memberTypeId: any /* types.CompactUUID */;
  name: string;
  email: string;
  phoneNumber: string;
  birthDate: string /* RFC3339 */;
  memberId: any /* types.CompactUUID */;
  createdAt: string /* RFC3339 */;
}
