// Code generated by tygo. DO NOT EDIT.

//////////
// source: form.go
/*
models.go
*/

export interface MemberType {
  id: string /* uuid */;
  name: string;
}
export interface GetFormResponse {
  formId: string /* uuid */;
  clubId: string;
  memberTypes: MemberType[];
  title: string;
  registrationOpens: string /* RFC3339 */;
}

//////////
// source: registration.go
/*
models.go
*/

export interface CreateRegistrationRequest {
  formId: string /* uuid */;
  memberTypeId: string /* uuid */;
  name: string;
  email: string;
  phoneNumber: string;
  birthDate: string /* RFC3339 */;
}
